image: docker.siemens.com/code-ops/poetry-docker

variables:
    http_proxy: $CODE_PROXY
    https_proxy: $CODE_PROXY
    no_proxy: .siemens.com

stages:
    - check

before_script:
    - poetry config virtualenvs.in-project true
    - poetry install --no-root

cache:
    paths:
        - .venv
    key: "${CI_COMMIT_REF_SLUG}"

format_and_style:
    stage: check
    script:
        - poetry run flake8 . --exclude=.venv
    except:
        - master

